name             'Vagrantchef'
maintainer       'Marcus Geißler'
maintainer_email 'marcus3006@gmail.com'
license          'All rights reserved'
description      'Installs/Configures .'
long_description 'Installs/Configures .'
version          '0.1.0'
